"""Generate a deterministic 128-input/8-class Solist-AI smoke-test model.

This deliberately simple synthetic problem validates the complete model
transport and inference path before vibration feature engineering is involved.
The exported golden values use bfloat16-quantized input and weights, matching
the precision selected for the MCU comparison.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np

INPUT_COUNT = 128
HIDDEN_COUNT = 32
CLASS_COUNT = 8
SEED = 20260716
DEFAULT_SIM_ALPHA = Path(r"D:\GitHub\IchiPing_solist_AI\sim_export\_alpha32_sim.npy")


def to_bfloat16_bits(values: np.ndarray) -> np.ndarray:
    """Return IEEE bfloat16 bits using round-to-nearest-even."""
    raw = np.asarray(values, dtype=np.float32).view(np.uint32)
    rounded = raw + np.uint32(0x7FFF) + ((raw >> 16) & 1)
    return (rounded >> 16).astype(np.uint16)


def from_bfloat16_bits(bits: np.ndarray) -> np.ndarray:
    return (np.asarray(bits, dtype=np.uint32) << 16).view(np.float32)


def quantize_bfloat16(values: np.ndarray) -> np.ndarray:
    return from_bfloat16_bits(to_bfloat16_bits(values))


def make_dataset(samples_per_class: int = 48, seed: int = SEED):
    """Create separated classes, each exciting its own input band."""
    rng = np.random.default_rng(seed)
    features, labels = [], []
    for label in range(CLASS_COUNT):
        signature = np.full(INPUT_COUNT, -0.30, dtype=np.float32)
        start = label * (INPUT_COUNT // CLASS_COUNT)
        signature[start : start + INPUT_COUNT // CLASS_COUNT] = 0.85
        signature += 0.08 * np.sin(np.arange(INPUT_COUNT) * (label + 1) * np.pi / 32)
        for _ in range(samples_per_class):
            features.append(signature + rng.normal(0, 0.055, INPUT_COUNT))
            labels.append(label)
    order = rng.permutation(len(labels))
    return np.asarray(features, np.float32)[order], np.asarray(labels, np.int64)[order]


def hidden(features: np.ndarray, alpha: np.ndarray) -> np.ndarray:
    return np.clip(0.2 * (features @ alpha) + 0.5, 0.0, 1.0)


def load_official_sim_alpha(path: Path = DEFAULT_SIM_ALPHA) -> np.ndarray:
    """Load seed=1 alpha captured from the official Solist-AI Simulator."""
    source = np.load(path, allow_pickle=False)
    if source.ndim != 2 or source.shape[0] < INPUT_COUNT or source.shape[1] < HIDDEN_COUNT:
        raise ValueError(f"official Simulator alpha must cover {INPUT_COUNT}x{HIDDEN_COUNT}")
    return np.asarray(source[:INPUT_COUNT, :HIDDEN_COUNT], dtype=np.float32)


def train_model(features: np.ndarray, labels: np.ndarray, seed: int = SEED,
                alpha_path: Path = DEFAULT_SIM_ALPHA):
    """Train the Solist one-hidden-layer topology (fixed alpha, learned beta)."""
    del seed  # dataset seed is separate; alpha is the official Simulator seed=1 projection.
    alpha = load_official_sim_alpha(alpha_path)
    h = hidden(features, alpha).astype(np.float64)
    targets = np.eye(CLASS_COUNT)[labels]
    beta = np.linalg.solve(h.T @ h + 0.01 * np.eye(HIDDEN_COUNT), h.T @ targets)
    return alpha, beta.astype(np.float32)


def mcu_reference(features: np.ndarray, alpha: np.ndarray, beta: np.ndarray) -> np.ndarray:
    """Reference path with bfloat16 boundaries and float32 accumulation."""
    xq = quantize_bfloat16(features)
    aq = quantize_bfloat16(alpha)
    bq = quantize_bfloat16(beta)
    hq = quantize_bfloat16(np.clip(0.2 * (xq @ aq) + 0.5, 0.0, 1.0))
    return quantize_bfloat16(hq @ bq)


def _c_array(name: str, bits: np.ndarray, columns: int = 12, declaration: str | None = None) -> str:
    flat = np.asarray(bits).reshape(-1)
    lines = []
    for offset in range(0, len(flat), columns):
        values = ", ".join(f"0x{int(v):04X}" for v in flat[offset : offset + columns])
        lines.append(f"    {values},")
    array_decl = declaration or f"{name}[{len(flat)}]"
    return f"static const int16_t {array_decl} = {{\n" + "\n".join(lines) + "\n};\n"


def export_header(path: Path, alpha: np.ndarray, beta: np.ndarray, cases: np.ndarray) -> None:
    content = """/* Generated by python -m sim.dummy_model_pipeline. Do not edit. */
#ifndef APAN_DUMMY_MODEL_H
#define APAN_DUMMY_MODEL_H
#include <stdint.h>
#define APAN_DUMMY_INPUT_SIZE 128
#define APAN_DUMMY_HIDDEN_SIZE 32
#define APAN_DUMMY_OUTPUT_SIZE 8
#define APAN_DUMMY_CASE_COUNT 8
#define APAN_DUMMY_SEED 1
#define APAN_DUMMY_ACTIVATION 1
#define APAN_DUMMY_LOSS 1
#define APAN_DUMMY_SCALE_ALPHA_BF16 ((int16_t)0x3E52)
"""
    content += _c_array("apan_dummy_alpha", to_bfloat16_bits(alpha))
    content += _c_array("apan_dummy_beta", to_bfloat16_bits(beta))
    content += _c_array("apan_dummy_inputs", to_bfloat16_bits(cases),
                        declaration="apan_dummy_inputs[APAN_DUMMY_CASE_COUNT][APAN_DUMMY_INPUT_SIZE]")
    content += "#endif\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="ascii")


def generate(output_dir: Path, header: Path, seed: int = SEED,
             alpha_path: Path = DEFAULT_SIM_ALPHA) -> dict:
    features, labels = make_dataset(seed=seed)
    alpha, beta = train_model(features, labels, seed, alpha_path)
    scores = mcu_reference(features, alpha, beta)
    accuracy = float(np.mean(np.argmax(scores, axis=1) == labels))

    # One stable, non-training-order-dependent comparison vector per class.
    cases = []
    case_inputs = []
    for label in range(CLASS_COUNT):
        index = int(np.flatnonzero(labels == label)[0])
        case_input = features[index]
        simulator_output = hidden(case_input[None, :], alpha) @ beta
        output = mcu_reference(case_input[None, :], alpha, beta)[0]
        case_inputs.append(case_input)
        cases.append({
            "board_case_id": label,
            "case_id": f"dummy_class_{label}",
            "expected_class": label,
            "predicted_class": int(np.argmax(output)),
            "input": quantize_bfloat16(case_input).astype(float).tolist(),
            "simulator_outputs_float32": simulator_output[0].astype(float).tolist(),
            "outputs": output.astype(float).tolist(),
            "max_quantization_delta": float(np.max(np.abs(simulator_output[0] - output))),
        })

    output_dir.mkdir(parents=True, exist_ok=True)
    np.savez(output_dir / "model.npz", alpha=alpha, beta=beta,
             alpha_bf16=to_bfloat16_bits(alpha), beta_bf16=to_bfloat16_bits(beta))
    np.savez(output_dir / "dummy_dataset.npz", features=features, labels=labels)
    np.savez(output_dir / "golden_cases.npz", inputs=np.asarray(case_inputs),
             outputs=np.asarray([case["outputs"] for case in cases], np.float32))
    export_header(header, alpha, beta, np.asarray(case_inputs))
    model_hash = hashlib.sha256((output_dir / "model.npz").read_bytes()).hexdigest()
    golden = {
        "metadata": {
            "model": "apan_dummy_128x32x8",
            "seed": seed,
            "input_count": INPUT_COUNT,
            "hidden_count": HIDDEN_COUNT,
            "output_count": CLASS_COUNT,
            "activation": "hard_sigmoid",
            "loss": "mse",
            "precision": "bfloat16 boundaries, float32 accumulation reference",
            "training_accuracy": accuracy,
            "model_sha256": model_hash,
            "alpha_origin": "ROHM official Solist-AI Simulator seed=1 capture",
            "alpha_source": str(alpha_path),
            "alpha_scale_max": float(np.max(np.abs(alpha))),
        },
        "cases": cases,
    }
    (output_dir / "golden_outputs.json").write_text(
        json.dumps(golden, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return golden


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path("data/dummy_model"))
    parser.add_argument("--header", type=Path,
                        default=Path("firmware/AcrylicPanCollector/generated/apan_dummy_model.h"))
    parser.add_argument("--seed", type=int, default=SEED)
    parser.add_argument("--alpha", type=Path, default=DEFAULT_SIM_ALPHA,
                        help="official Simulator seed=1 alpha .npy")
    args = parser.parse_args()
    result = generate(args.output_dir, args.header, args.seed, args.alpha)
    print(f"model={result['metadata']['model']}")
    print(f"training_accuracy={result['metadata']['training_accuracy']:.4f}")
    print(f"golden_cases={len(result['cases'])}")
    print(f"golden={args.output_dir / 'golden_outputs.json'}")
    print(f"header={args.header}")


if __name__ == "__main__":
    main()
