"""Export the on-site calibration prior for the deployed 12-area firmware model.

The firmware updates beta with a float32 OS-ELM on the CPU (P and beta live in
the board FRAM).  This script writes the starting matrix
``P0 = w (G + lambda I)^-1`` for the deployed model, where ``G`` is the
hidden-layer Gram matrix of every event the deployed beta was trained on, and
a host-test golden sequence computed in float64.
"""

from __future__ import annotations

import argparse
import re
import zlib
from pathlib import Path

import numpy as np

from .dummy_model_pipeline import from_bfloat16_bits, quantize_bfloat16, to_bfloat16_bits
from .odl_calibration_experiment import (
    _load_features,
    calibration_pool,
    draw_calibration,
    hidden_layer,
    initial_p,
    os_elm_update,
)
from .real_model_pipeline import FeatureScaler, _c_float_array

CALIBRATION_WEIGHT = 30.0
PRIOR_RIDGE = 1.0
GOLDEN_SESSION = "20260720_215533_aa9943ae"
GOLDEN_PER_CLASS = 2
DEFAULT_MODEL = Path("artifacts/real_model_400x300x5_12class_max_data_20260828/model.npz")
DEFAULT_MODEL_HEADER = Path("firmware/AcrylicPanCollector/generated/apan_12class_model.h")
DEFAULT_PRIOR_HEADER = Path("firmware/AcrylicPanCollector/generated/apan_calibration_prior.h")
DEFAULT_GOLDEN_HEADER = Path("firmware/AcrylicPanCollector/generated/apan_calibration_golden.h")
DEFAULT_CACHE = Path("artifacts/odl_calibration_experiment_20260927/features_cache.npz")


def header_beta_bits(path: Path) -> np.ndarray:
    """Read the deployed bfloat16 beta bits from the generated model header."""
    text = path.read_text(encoding="ascii")
    match = re.search(r"apan_model_beta\[\d+\] = \{(.*?)\};", text, re.S)
    if match is None:
        raise ValueError(f"{path}: apan_model_beta was not found")
    values = [int(value, 16) for value in re.findall(r"0x[0-9A-Fa-f]{4}", match.group(1))]
    return np.asarray(values, dtype=np.uint16)


def model_crc32(beta_bits: np.ndarray) -> int:
    """CRC32 of the little-endian beta bits; identifies the factory model."""
    return zlib.crc32(np.asarray(beta_bits, dtype="<u2").tobytes()) & 0xFFFFFFFF


def _c_bits_array(name: str, bits: np.ndarray, declaration: str) -> str:
    flat = np.asarray(bits, dtype=np.uint16).reshape(-1)
    lines = [
        "    " + ", ".join(f"0x{int(value):04X}" for value in flat[offset : offset + 12]) + ","
        for offset in range(0, len(flat), 12)
    ]
    return f"static const uint16_t {declaration} = {{\n" + "\n".join(lines) + "\n};\n"


def export(model_path: Path, model_header: Path, sessions_root: Path, cache: Path,
           prior_header: Path, golden_header: Path) -> dict:
    with np.load(model_path, allow_pickle=False) as model:
        alpha = np.asarray(model["alpha"], dtype=np.float32)
        beta_bits = np.asarray(model["beta_bf16"], dtype=np.uint16)
        scaler = FeatureScaler(np.asarray(model["feature_mean"]), np.asarray(model["feature_scale"]))
    deployed_bits = header_beta_bits(model_header)
    if not np.array_equal(deployed_bits, beta_bits.reshape(-1)):
        raise ValueError(f"{model_path} beta does not match {model_header}")
    hidden_count, output_count = beta_bits.shape

    dataset, features = _load_features(sessions_root, cache)
    labels = np.asarray(dataset.labels, dtype=np.int64)
    factory_x = scaler.transform(features)
    p0 = initial_p(hidden_layer(factory_x, alpha), PRIOR_RIDGE, CALIBRATION_WEIGHT)
    p0 = p0.astype(np.float32)
    crc = model_crc32(beta_bits)

    prior = f"""/* Generated by python -m sim.odl_calibration_prior. Do not edit. */
#ifndef APAN_CALIBRATION_PRIOR_H
#define APAN_CALIBRATION_PRIOR_H
#include <stdint.h>
#define APAN_CALIBRATION_HIDDEN_SIZE {hidden_count}U
#define APAN_CALIBRATION_OUTPUT_SIZE {output_count}U
/* Factory beta identity: CRC32 of apan_model_beta (little-endian bfloat16 bits). */
#define APAN_CALIBRATION_MODEL_CRC32 (0x{crc:08X}UL)
/* P0 = w (G + lambda I)^-1 over the {len(labels)} factory events; w = {CALIBRATION_WEIGHT:g}, lambda = {PRIOR_RIDGE:g}.
   Row-major float32; each calibration hit then counts as w factory events. */
"""
    prior += _c_float_array("apan_calibration_p0", p0)
    prior += "#endif\n"
    prior_header.parent.mkdir(parents=True, exist_ok=True)
    prior_header.write_text(prior, encoding="ascii")

    members = np.flatnonzero(dataset.session_ids == GOLDEN_SESSION)
    pool = calibration_pool(labels, dataset.repetitions, np.asarray(dataset.point_names), members)
    chosen = draw_calibration(pool, GOLDEN_PER_CLASS, seed=0)
    input_bits = to_bfloat16_bits(factory_x[chosen])
    hidden = quantize_bfloat16(hidden_layer(from_bfloat16_bits(input_bits), alpha))
    beta0 = from_bfloat16_bits(beta_bits).astype(np.float64)
    beta, p = os_elm_update(beta0, p0, hidden, labels[chosen], "float64")
    count = len(chosen)
    golden = f"""/* Generated by python -m sim.odl_calibration_prior for host tests. Do not edit. */
#ifndef APAN_CALIBRATION_GOLDEN_H
#define APAN_CALIBRATION_GOLDEN_H
#include <stdint.h>
/* {count} guided hits from session {GOLDEN_SESSION}; expected values are float64. */
#define APAN_CALIBRATION_GOLDEN_COUNT {count}U
static const uint8_t apan_calibration_golden_targets[{count}] = {{
    {", ".join(str(int(value)) for value in labels[chosen])}
}};
"""
    golden += _c_bits_array("apan_calibration_golden_inputs", input_bits,
                            f"apan_calibration_golden_inputs[{count}][{input_bits.shape[1]}]")
    golden += _c_float_array("apan_calibration_golden_hidden", hidden)
    golden += _c_float_array("apan_calibration_golden_beta", beta)
    golden += _c_float_array("apan_calibration_golden_p", p)
    golden += "#endif\n"
    golden_header.write_text(golden, encoding="ascii")
    return {
        "model_crc32": f"0x{crc:08X}",
        "factory_events": int(len(labels)),
        "p0_diagonal_range": [float(np.diag(p0).min()), float(np.diag(p0).max())],
        "golden_hits": count,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sessions", type=Path, default=Path("data/raw/sessions"))
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL)
    parser.add_argument("--model-header", type=Path, default=DEFAULT_MODEL_HEADER)
    parser.add_argument("--feature-cache", type=Path, default=DEFAULT_CACHE)
    parser.add_argument("--prior-header", type=Path, default=DEFAULT_PRIOR_HEADER)
    parser.add_argument("--golden-header", type=Path, default=DEFAULT_GOLDEN_HEADER)
    args = parser.parse_args()
    print(export(args.model, args.model_header, args.sessions, args.feature_cache,
                 args.prior_header, args.golden_header))


if __name__ == "__main__":
    main()
