"""Screen the one-hidden-layer Solist-AI topology on synthetic modal features.

This is intentionally a feasibility check only.  Samples are generated by
perturbing the FEA modal-coupling vectors with hit-force scaling and noise; real
panel measurements remain the acceptance test.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


def hard_sigmoid(value: np.ndarray) -> np.ndarray:
    return np.clip(0.2 * value + 0.5, 0.0, 1.0)


def fit_scores(x_train, targets, x_test, hidden: int, seed: int, ridge: float = 1e-2):
    rng = np.random.default_rng(seed)
    inputs = x_train.shape[1]
    outputs = targets.shape[1]
    alpha = rng.uniform(-0.2, 0.2, size=(inputs, hidden))
    bias = np.zeros(hidden)
    h_train = hard_sigmoid(x_train @ alpha + bias)
    beta = np.linalg.solve(h_train.T @ h_train + ridge * np.eye(hidden), h_train.T @ targets)
    return hard_sigmoid(x_test @ alpha + bias) @ beta


def fit_predict(x_train, y_train, x_test, hidden: int, seed: int, ridge: float = 1e-2):
    targets = np.eye(int(y_train.max()) + 1)[y_train]
    return np.argmax(fit_scores(x_train, targets, x_test, hidden, seed, ridge), axis=1)


def make_samples(base: np.ndarray, count: int, rng: np.random.Generator):
    samples, labels = [], []
    for label, signature in enumerate(base):
        for _ in range(count):
            force = rng.uniform(0.55, 1.45)
            noise = rng.normal(0.0, 0.045, size=signature.shape)
            sample = np.maximum(signature * force + noise, 0.0)
            sample /= max(np.linalg.norm(sample), 1e-9)
            samples.append(sample)
            labels.append(label)
    order = rng.permutation(len(samples))
    return np.asarray(samples)[order], np.asarray(labels)[order]


def make_multihit_samples(base: np.ndarray, count: int, rng: np.random.Generator):
    """Generate every single and two-hit combination using linear superposition."""
    combinations = [(i,) for i in range(len(base))]
    combinations += [(i, j) for i in range(len(base)) for j in range(i + 1, len(base))]
    samples, targets = [], []
    for combination in combinations:
        for _ in range(count):
            sample = np.zeros(base.shape[1])
            target = np.zeros(len(base))
            for label in combination:
                sample += base[label] * rng.uniform(0.70, 1.30)
                target[label] = 1.0
            sample += rng.normal(0.0, 0.04, size=sample.shape)
            sample = np.maximum(sample, 0.0)
            sample /= max(np.linalg.norm(sample), 1e-9)
            samples.append(sample)
            targets.append(target)
    order = rng.permutation(len(samples))
    return np.asarray(samples)[order], np.asarray(targets)[order]


def decode_multihit(scores: np.ndarray, threshold: float) -> np.ndarray:
    predicted = scores >= threshold
    for row, values in zip(predicted, scores):
        if not row.any():
            row[np.argmax(values)] = True
        if row.sum() > 2:
            keep = np.argsort(values)[-2:]
            row[:] = False
            row[keep] = True
    return predicted


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--modal-results", type=Path, default=Path("web/assets/simulation/results.json"))
    parser.add_argument("--output", type=Path, default=Path("web/assets/simulation/solist-feasibility.json"))
    args = parser.parse_args()
    modal = json.loads(args.modal_results.read_text(encoding="utf-8"))
    base = np.asarray([hit["modal_coupling"] for hit in modal["hits"]], dtype=float)
    rng = np.random.default_rng(20260713)
    x_train, y_train = make_samples(base, 80, rng)
    x_test, y_test = make_samples(base, 40, rng)
    cases = []
    for hidden in (8, 16, 32, 64):
        scores = []
        for seed in range(1, 11):
            predicted = fit_predict(x_train, y_train, x_test, hidden, seed)
            scores.append(float(np.mean(predicted == y_test)))
        cases.append(
            {
                "hidden_nodes": hidden,
                "node_total": int(base.shape[1] + hidden + base.shape[0]),
                "accuracy_mean": round(float(np.mean(scores)), 4),
                "accuracy_min": round(float(np.min(scores)), 4),
                "accuracy_max": round(float(np.max(scores)), 4),
            }
        )
    multi_train_x, multi_train_y = make_multihit_samples(base, 50, rng)
    multi_test_x, multi_test_y = make_multihit_samples(base, 25, rng)
    multihit_cases = []
    for hidden in (32, 64, 128):
        exact_scores, label_f1_scores = [], []
        for seed in range(1, 11):
            train_scores = fit_scores(multi_train_x, multi_train_y, multi_train_x, hidden, seed)
            thresholds = np.linspace(0.25, 0.75, 21)
            threshold = max(
                thresholds,
                key=lambda value: np.mean(np.all(decode_multihit(train_scores, value) == multi_train_y, axis=1)),
            )
            test_scores = fit_scores(multi_train_x, multi_train_y, multi_test_x, hidden, seed)
            predicted = decode_multihit(test_scores, float(threshold))
            exact_scores.append(float(np.mean(np.all(predicted == multi_test_y, axis=1))))
            tp = np.sum(predicted & (multi_test_y == 1))
            fp = np.sum(predicted & (multi_test_y == 0))
            fn = np.sum((~predicted) & (multi_test_y == 1))
            label_f1_scores.append(float(2 * tp / max(2 * tp + fp + fn, 1)))
        multihit_cases.append(
            {
                "hidden_nodes": hidden,
                "node_total": int(base.shape[1] + hidden + base.shape[0]),
                "exact_set_accuracy_mean": round(float(np.mean(exact_scores)), 4),
                "exact_set_accuracy_min": round(float(np.min(exact_scores)), 4),
                "label_f1_mean": round(float(np.mean(label_f1_scores)), 4),
            }
        )
    output = {
        "status": "synthetic feasibility only",
        "input_nodes": int(base.shape[1]),
        "output_nodes": int(base.shape[0]),
        "activation": "hard sigmoid",
        "seeds": 10,
        "train_samples": int(len(y_train)),
        "test_samples": int(len(y_test)),
        "cases": cases,
        "simultaneous_hits": {
            "classes": "8 singles + 28 two-hit combinations",
            "target": "8-output multi-hot",
            "train_samples": int(len(multi_train_y)),
            "test_samples": int(len(multi_test_y)),
            "cases": multihit_cases,
        },
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(output, ensure_ascii=False))


if __name__ == "__main__":
    main()
